version: '3.4'

services:
  obudaichatbot:
    image: chatbot
    container_name: oechatbot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      - FLASK_APP=qa.py
